name: project deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deployment event triggering through HTTP request
        run: curl http://$server_ip:$deployment_port/update?branch=$${GITHUB_REF##*/}